# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chriswk
email: blog@chriswk.no
description: Programming and blogging about it (hopefully)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chriswk.github.io" # the base hostname & protocol for your site
twitter_username: chriswk
github_username:  chriswk
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-coffeescript
permalink: /:year/:month/:title
# Build settings
markdown: kramdown
google_analytic_id: UA-76743436-1
paginate: 5
